apiVersion: skaffold/v2beta14
kind: Config
deploy:
   kubectl:
      manifests:
         - ./infr/k8s/*
build:
   local:
      push: false
   artifacts:
      - image: jonatlop07/client
        context: client
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: 'src/**/*.js'
                dest: .
      - image: jonatlop07/comments
        context: comments
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: '*.js'
                dest: .
      - image: jonatlop07/event-bus
        context: event-bus
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: '*.js'
                dest: .
      - image: jonatlop07/moderation
        context: moderation
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: '*.js'
                dest: .
      - image: jonatlop07/posts
        context: posts
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: '*.js'
                dest: .
      - image: jonatlop07/query
        context: query
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: '*.js'
                dest: .
